### ISSUE TITLE
.md files for json data... why not just use json files

### ISSUE THREAD

**Issue by Moro-Code** [MarcoGoC/nextjs-test-app#3]
So I notice that for the data files you have they are basically just json files but you have them as markdown files. I'm assuming this data is from an API as well. Perhaps server side rendering was more ideal than server side generation.

**Comment by MarcoGoC** [comment]
right, I was following the blog and didnt renamed the files. some of the files were for testing, instead of hitting the api over and over. 
4 of those files is mostly historical data.

**Comment by Moro-Code** [comment]
sounds good !
